version: "3.1"
services:

  api:
    build: ./
    ports:
      - 8086:8080
    environment:
      NODE_ENV: dev
      DB_NAME: example
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: root
      DB_PWD: example
      MONGODB_URL: mongodb://root:example@mongo:27017
    volumes:
      - ./:/home/node/app
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8100:8081
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example